name: Trunk

on:
  push:
    paths:
      - 'debian-gfortran/trunk/*'
      - '.github/workflows/debian-gfortran-trunk.yml'
  schedule:
    - cron: '0 0 * * 2'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./debian-gfortran/trunk/Dockerfile
        push: true
        tags: ghcr.io/mehdichinoune/debian-gfortran-testing:trunk
