name: Trunk

on:
  push:
    paths:
      - 'debian-gfortran/trunk/*'
  schedule:
    - cron: '0 0 * * 2'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: ./debian-gfortran/trunk/Dockerfile
        push: true
        tags: chinoune/debian-gfortran-testing:trunk
